
spring :
  application :
    name : eureka-discovery-service
    
server :
  port : 9083
  
eureka :
  client :
    registerWithEureka : false
    fetchRegistry : false
    service-url :
      defaultZone : http://localhost:9083/eureka
      